version: "3.7"

services:
    # Laravel App (PHP)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # Nginx
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - laravel
    postgres:
        image: postgres:15
        container_name: postgres
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: homecare
            POSTGRES_USER: homedev
            POSTGRES_PASSWORD: secret123
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    pgdata:
